# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetEaseCloudMusic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Moya'
pod 'Kingfisher'
pod 'MBProgressHUD'
  # Pods for NetEaseCloudMusic

  target 'NetEaseCloudMusicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetEaseCloudMusicUITests' do
    # Pods for testing
  end

end
