# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ComprehensivePractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Moya'
pod 'Kingfisher'
pod 'MBProgressHUD'
pod 'MJRefresh'
  # Pods for ComprehensivePractice

  target 'ComprehensivePracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ComprehensivePracticeUITests' do
    # Pods for testing
  end

end
