# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PerfactNet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#pod 'Alamofire'
pod 'SVProgressHUD'
pod 'Moya'
  # Pods for PerfactNet

  target 'PerfactNetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PerfactNetUITests' do
    # Pods for testing
  end

end
